baseurl = "https://antonyho.net"
title = "Antony Ho"

theme = "coder-portfolio"

DefaultContentLanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Antony Ho"
    description = "Antony's Personal Website"
    keywords = "blog,developer,personal"
    info = "SOFTWARE ENGINEER"
    avatarurl = "images/avatar.jpg"
    footercontent = "I'm a software engineer. With broad range of interests, pretty strong conscience, a little bit sense of humour."
    fixedbarContent = ""
    fixedbarContentAfter = ""

    hideCredits = true
    hideCopyright = true

    snsShare = false

    thumbnail = "images/avatar.jpg"

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"


    GithubID = "antonyho"
    BitbucketID = "antonyho"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/antonyho/"
[[params.social]]
    name = "Stack Overflow"
    weight = 2
    url = "https://stackexchange.com/users/435981/antony-h"
[[params.social]]
    name = "Tech Note"
    weight = 3
    url = "http://notes.antonyho.net/"

[languages]
    [languages.en]
        languagecode = "en"
        languagename = "English" # The language name to be displayed in the selector.
        title = "Antony Ho"

        # You can configure the theme parameter for each language.
        [languages.en.params]
            author = "Antony Ho"
            info = "SOFTWARE ENGINEER"
            description = "Antony's Personal Website"
            keywords = "developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

            [[languages.en.menu.main]]
                name = "About"
                weight = 1.0
                url = "/about"

            [[languages.en.menu.main]]
                name = "Notes"
                weight = 2.0
                url = "http://notes.antonyho.net/"

            [[languages.en.menu.main]]
                name = "Footprints"
                weight = 3
                url = "/footprints"

            [[languages.en.menu.main]]
                name = "Works"
                weight = 3
                url = "/works"

            [[languages.en.menu.main]]
                name = "Contact"
                weight = 5
                url = "/contact"
